In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import os
import random
import warnings
warnings.filterwarnings("ignore")

In [2]:
np.random.seed(42)
random.seed(42)
os.environ['PYTHONHASHSEED'] = '0'

In [3]:
%cd '/content/drive/MyDrive/Colab Notebooks/TIL'

/content/drive/MyDrive/Colab Notebooks/TIL

In [4]:
data = pd.read_csv('./data/bitstampUSD.csv')

In [5]:
data

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1325317920,4.39,4.39,4.39,4.39,0.455581,2.000000,4.390000
1,1325317980,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1325318040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1325318100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1325318160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
4857372,1617148560,58714.31,58714.31,58686.00,58686.00,1.384487,81259.372187,58692.753339
4857373,1617148620,58683.97,58693.43,58683.97,58685.81,7.294848,428158.146640,58693.226508
4857374,1617148680,58693.43,58723.84,58693.43,58723.84,1.705682,100117.070370,58696.198496
4857375,1617148740,58742.18,58770.38,58742.18,58760.59,0.720415,42332.958633,58761.866202
4857376,1617148800,58767.75,58778.18,58755.97,58778.18,2.712831,159417.751000,58764.349363

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4857377 entries, 0 to 4857376
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   Timestamp          int64
 1   Open               float64
 2   High               float64
 3   Low                float64
 4   Close              float64
 5   Volume_(BTC)       float64
 6   Volume_(Currency)  float64
 7   Weighted_Price     float64
dtypes: float64(7), int64(1)
memory usage: 296.5 MB

In [8]:
data.isnull().sum()

Timestamp                  0
Open                 1243608
High                 1243608
Low                  1243608
Close                1243608
Volume_(BTC)         1243608
Volume_(Currency)    1243608
Weighted_Price       1243608
dtype: int64

In [16]:
data.index = pd.to_datetime(data.Timestamp, unit='s')
data

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
Timestamp,,,,,,,,
2011-12-31 07:52:00,1325317920,4.39,4.39,4.39,4.39,0.455581,2.000000,4.390000
2011-12-31 07:53:00,1325317980,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:54:00,1325318040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:55:00,1325318100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:56:00,1325318160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2021-03-30 23:56:00,1617148560,58714.31,58714.31,58686.00,58686.00,1.384487,81259.372187,58692.753339
2021-03-30 23:57:00,1617148620,58683.97,58693.43,58683.97,58685.81,7.294848,428158.146640,58693.226508
2021-03-30 23:58:00,1617148680,58693.43,58723.84,58693.43,58723.84,1.705682,100117.070370,58696.198496
2021-03-30 23:59:00,1617148740,58742.18,58770.38,58742.18,58760.59,0.720415,42332.958633,58761.866202
2021-03-31 00:00:00,1617148800,58767.75,58778.18,58755.97,58778.18,2.712831,159417.751000,58764.349363

In [17]:
data = data.drop(['Timestamp'], axis=1)
data

,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
Timestamp,,,,,,,
2011-12-31 07:52:00,4.39,4.39,4.39,4.39,0.455581,2.000000,4.390000
2011-12-31 07:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:54:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:55:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31 07:56:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2021-03-30 23:56:00,58714.31,58714.31,58686.00,58686.00,1.384487,81259.372187,58692.753339
2021-03-30 23:57:00,58683.97,58693.43,58683.97,58685.81,7.294848,428158.146640,58693.226508
2021-03-30 23:58:00,58693.43,58723.84,58693.43,58723.84,1.705682,100117.070370,58696.198496
2021-03-30 23:59:00,58742.18,58770.38,58742.18,58760.59,0.720415,42332.958633,58761.866202
2021-03-31 00:00:00,58767.75,58778.18,58755.97,58778.18,2.712831,159417.751000,58764.349363

In [18]:
data = data.resample('D').mean()
data

,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
Timestamp,,,,,,,
2011-12-31,4.465000,4.482500,4.465000,4.482500,23.829470,106.330084,4.471603
2012-01-01,4.806667,4.806667,4.806667,4.806667,7.200667,35.259720,4.806667
2012-01-02,5.000000,5.000000,5.000000,5.000000,19.048000,95.240000,5.000000
2012-01-03,5.252500,5.252500,5.252500,5.252500,11.004660,58.100651,5.252500
2012-01-04,5.200000,5.223333,5.200000,5.223333,11.914807,63.119577,5.208159
...,...,...,...,...,...,...,...
2021-03-27,55193.240643,55219.665031,55168.757372,55195.415367,1.823877,100884.732367,55193.357260
2021-03-28,55833.608471,55857.735342,55810.425126,55835.012863,1.447939,80632.115263,55832.958824
2021-03-29,56914.886595,56946.213593,56885.242967,56915.629993,3.732887,213754.555988,56913.993819
2021-03-30,58347.805624,58371.955310,58323.956690,58349.357087,2.363999,138231.241926,58346.912268
2021-03-31,58767.750000,58778.180000,58755.970000,58778.180000,2.712831,159417.751000,58764.349363

In [20]:
data = data.dropna()

In [21]:
from sklearn.preprocessing import RobustScaler

rob_scaler = RobustScaler()

for col in data.columns:
    data[col] = rob_scaler.fit_transform(data[col].values.reshape(-1, 1))

In [22]:
data

,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
Timestamp,,,,,,,
2011-12-31,-0.099101,-0.099060,-0.099124,-0.099099,1.919561,-0.196897,-0.099097
2012-01-01,-0.099053,-0.099014,-0.099075,-0.099052,-0.049931,-0.198978,-0.099049
2012-01-02,-0.099025,-0.098987,-0.099047,-0.099025,1.353250,-0.197222,-0.099022
2012-01-03,-0.098989,-0.098950,-0.099011,-0.098989,0.400609,-0.198309,-0.098986
2012-01-04,-0.098996,-0.098955,-0.099019,-0.098993,0.508405,-0.198162,-0.098992
...,...,...,...,...,...,...,...
2021-03-27,7.787505,7.785233,7.789185,7.788185,-0.686750,2.753435,7.787350
2021-03-28,7.879015,7.876344,7.880941,7.879589,-0.731276,2.160531,7.878749
2021-03-29,8.033533,8.031770,8.034637,8.034019,-0.460650,6.057749,8.033228
2021-03-30,8.238300,8.235355,8.240368,8.238912,-0.622779,3.846771,8.237991
2021-03-31,8.298311,8.293361,8.302144,8.300195,-0.581464,4.467015,8.297642

In [26]:
train = data.iloc[:-365]
test = data.iloc[-365:]

In [27]:
X_train = train.drop(columns=['Weighted_Price'])
y_train = train.Weighted_Price

X_test = test.drop(columns=['Weighted_Price'])
y_test = test.Weighted_Price

# ML with scikit-learn

In [32]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [29]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10)
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=10)

In [30]:
y_pred = rf.predict(X_test)
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

1.9817887287650173

In [33]:
knn = KNeighborsRegressor(n_neighbors=2)
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=2)

In [34]:
y_pred = knn.predict(X_test)
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

2.028375189330333

# DL with tensorflow.keras

In [43]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Model, layers, optimizers, datasets

class LSTM(Model):
    def __init__(self, units):
        super(LSTM, self).__init__()
        
        self.sequential = tf.keras.Sequential([
            layers.LSTM(units, activation='relu'),
            layers.BatchNormalization(),
            layers.Dense(1)
        ])

    def call(self, x):
        out = self.sequential(x)
        return out

In [36]:
X_train = X_train.values
y_train = y_train.values

X_test = X_test.values
y_test = y_test.values

In [37]:
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])

In [44]:
model = LSTM(10)

WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.

In [45]:
lr = 1e-3

model.compile(optimizer=optimizers.Adam(learning_rate=lr),
              loss='mse')

In [47]:
batch_size = 32
epochs = 10

model.fit(X_train, y_train, validation_split=0.2, batch_size=batch_size, epochs=epochs, shuffle=True, verbose=1)

Epoch 1/10
76/76 [==============================] - 6s 8ms/step - loss: 0.4913 - val_loss: 0.5507
Epoch 2/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0610 - val_loss: 0.5199
Epoch 3/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0300 - val_loss: 0.5399
Epoch 4/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0225 - val_loss: 0.4036
Epoch 5/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0190 - val_loss: 0.3117
Epoch 6/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0170 - val_loss: 0.3339
Epoch 7/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0136 - val_loss: 0.1692
Epoch 8/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0155 - val_loss: 0.1476
Epoch 9/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0135 - val_loss: 0.1017
Epoch 10/10
76/76 [==============================] - 0s 5ms/step - loss: 0.0109 - val_loss: 0.0272

In [48]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)
mean_squared_error(y_test, y_pred, squared=False)

12/12 [==============================] - 0s 2ms/step

1.3418515873549992

# Conclusion

DL > ML win!

But not always